"""
Curer Pre-Consultation AI Intake Bot
PDF generation for the Doctor's Briefing Card using fpdf2.
"""

from datetime import datetime

import streamlit as st
from fpdf import FPDF


class CurerPDF(FPDF):
    """Custom PDF class with Curer branding."""

    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        """Curer-branded header."""
        # Teal header bar
        self.set_fill_color(13, 148, 136)  # #0D9488
        self.rect(0, 0, 210, 20, "F")

        # Title text
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 14)
        self.set_y(5)
        self.cell(0, 10, "Curer - Doctor's Briefing Card", align="C")

        # Reset position
        self.set_y(25)

    def footer(self):
        """Footer with timestamp and branding."""
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(156, 163, 175)  # Gray
        timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p")
        self.cell(0, 10, f"Generated by Curer AI Intake | {timestamp} | Page {self.page_no()}", align="C")

    def add_section_title(self, title: str):
        """Add a styled section title."""
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(13, 148, 136)  # Teal
        self.cell(0, 8, title.upper(), new_x="LMARGIN", new_y="NEXT")
        # Thin teal line
        self.set_draw_color(204, 251, 241)  # Light teal
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(2)

    def add_section_content(self, content: str):
        """Add section body text."""
        self.set_font("Helvetica", "", 10)
        self.set_text_color(31, 41, 55)  # Dark gray
        self.multi_cell(0, 6, content)
        self.ln(4)

    def add_tags(self, items: list, is_red_flag: bool = False):
        """Add tag-style items."""
        self.set_font("Helvetica", "", 9)
        if is_red_flag:
            self.set_text_color(220, 38, 38)  # Red
            prefix = "! "
        else:
            self.set_text_color(15, 118, 110)  # Dark teal
            prefix = "* "

        for item in items:
            if item and item.strip() and item.lower() != "none":
                self.cell(0, 5, f"  {prefix}{item}", new_x="LMARGIN", new_y="NEXT")
        self.ln(4)

    def add_specialty_badge(self, specialty: str):
        """Add specialty badge(s) below header. Supports 'Spec1 + Spec2' format."""
        specialties = [s.strip() for s in specialty.split("+") if s.strip()]
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(13, 148, 136)
        label = "Specialties" if len(specialties) > 1 else "Specialty"
        self.cell(0, 8, f"{label}: {', '.join(specialties)}", new_x="LMARGIN", new_y="NEXT")
        self.ln(4)

    def add_severity_indicator(self, severity: str):
        """Add severity with visual indicator."""
        self.set_font("Helvetica", "B", 10)
        severity_lower = severity.lower()
        if "severe" in severity_lower or "high" in severity_lower:
            self.set_text_color(220, 38, 38)  # Red
        elif "moderate" in severity_lower or "medium" in severity_lower:
            self.set_text_color(146, 64, 14)  # Amber
        else:
            self.set_text_color(6, 95, 70)  # Green
        self.cell(0, 6, f"  {severity}", new_x="LMARGIN", new_y="NEXT")
        self.ln(4)


def generate_pdf(intake_data: dict, specialty: str) -> bytes | None:
    """Generate a Curer-branded PDF briefing card."""
    try:
        pdf = CurerPDF()
        pdf.add_page()

        # Specialty badge
        pdf.add_specialty_badge(specialty)

        # Patient Summary
        pdf.add_section_title("Patient Summary")
        pdf.add_section_content(intake_data.get("patient_summary", "No summary available"))

        # Chief Complaint
        pdf.add_section_title("Chief Complaint")
        pdf.add_section_content(intake_data.get("chief_complaint", "Not specified"))

        # Symptoms
        symptoms = intake_data.get("symptoms", [])
        if symptoms:
            pdf.add_section_title("Symptoms")
            pdf.add_tags(symptoms)

        # Duration
        pdf.add_section_title("Duration")
        pdf.add_section_content(intake_data.get("duration", "Not specified"))

        # Severity
        pdf.add_section_title("Severity")
        pdf.add_severity_indicator(intake_data.get("severity", "Not assessed"))

        # Relevant History
        pdf.add_section_title("Relevant History")
        pdf.add_section_content(intake_data.get("relevant_history", "None reported"))

        # Red Flags
        red_flags = intake_data.get("red_flags", [])
        if red_flags and any(rf.strip() for rf in red_flags if rf.lower() != "none"):
            pdf.add_section_title("Red Flags")
            pdf.add_tags(red_flags, is_red_flag=True)

        # Suggested Focus Areas
        focus_areas = intake_data.get("suggested_focus_areas", [])
        if focus_areas:
            pdf.add_section_title("Suggested Focus Areas")
            pdf.add_tags(focus_areas)

        # Output PDF bytes
        pdf_output = pdf.output()
        return bytes(pdf_output)

    except Exception as e:
        st.error("Error generating PDF. Please try resetting the conversation.")
        return None


def get_download_button(pdf_bytes: bytes):
    """Render a Streamlit download button for the PDF."""
    st.download_button(
        label=" Download Briefing Card (PDF)",
        data=pdf_bytes,
        file_name=f"curer_briefing_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf",
        mime="application/pdf",
        use_container_width=True,
    )
