"""
Curer Pre-Consultation AI Intake Bot
Custom CSS styles and briefing card renderer using Streamlit components.
"""

import streamlit as st
from datetime import datetime
import html as html_lib


def _safe(text: str) -> str:
    """Escape user content to prevent injection in markdown/HTML contexts."""
    if not text:
        return ""
    return html_lib.escape(str(text), quote=True)


def render_briefing_card(intake_data: dict, specialty: str):
    """Render the Doctor's Briefing Card using native Streamlit components."""

    # Extract data with safe defaults
    patient_summary = intake_data.get("patient_summary", "No summary available")
    chief_complaint = intake_data.get("chief_complaint", "Not specified")
    symptoms = intake_data.get("symptoms", [])
    duration = intake_data.get("duration", "Not specified")
    severity = intake_data.get("severity", "Not assessed")
    relevant_history = intake_data.get("relevant_history", "None reported")
    red_flags = intake_data.get("red_flags", [])
    focus_areas = intake_data.get("suggested_focus_areas", [])

    # Timestamp
    timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p")

    # Card container
    with st.container(border=True):
        # Header
        col_title, col_badge = st.columns([3, 1])
        with col_title:
            st.markdown("### 📋 Doctor's Briefing Card")
        with col_badge:
            st.markdown(
                f'<span style="background-color:#0D9488;color:white;padding:0.3rem 0.8rem;'
                f'border-radius:20px;font-size:0.85rem;font-weight:500;">{_safe(specialty)}</span>',
                unsafe_allow_html=True,
            )

        st.divider()

        # Patient Summary
        st.markdown("**PATIENT SUMMARY**")
        st.write(patient_summary)

        # Chief Complaint
        st.markdown("**CHIEF COMPLAINT**")
        st.write(chief_complaint)

        # Symptoms
        st.markdown("**SYMPTOMS**")
        if symptoms:
            symptom_pills = " ".join(
                f'`{s}`' for s in symptoms if s
            )
            st.markdown(symptom_pills)
        else:
            st.write("None reported")

        # Duration
        st.markdown("**DURATION**")
        st.write(duration)

        # Severity
        st.markdown("**SEVERITY**")
        severity_lower = severity.lower()
        if "severe" in severity_lower or "high" in severity_lower:
            st.error(severity)
        elif "moderate" in severity_lower or "medium" in severity_lower:
            st.warning(severity)
        else:
            st.success(severity)

        # Relevant History
        st.markdown("**RELEVANT HISTORY**")
        st.write(relevant_history)

        # Red Flags
        if red_flags and any(rf.strip() for rf in red_flags if rf.lower() != "none"):
            st.markdown("**⚠️ RED FLAGS**")
            for rf in red_flags:
                if rf.strip() and rf.lower() != "none":
                    st.error(f"⚠️ {rf}")

        # Suggested Focus Areas
        st.markdown("**SUGGESTED FOCUS AREAS**")
        if focus_areas:
            focus_pills = " ".join(
                f'`{fa}`' for fa in focus_areas if fa
            )
            st.markdown(focus_pills)
        else:
            st.write("General assessment recommended")

        # Timestamp
        st.caption(f"Generated by Curer AI Intake • {timestamp}")
